# Generated by Django 4.1.3 on 2022-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='validade',
            field=models.CharField(max_length=5),
        ),
    ]
