# Generated by Django 4.1.1 on 2022-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
