# Generated by Django 4.1.1 on 2022-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_alter_cliente_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
    ]
