# Generated by Django 4.1.1 on 2022-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_imagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='tipoCartão',
            new_name='tipoCartao',
        ),
        migrations.AlterField(
            model_name='imagens',
            name='foto',
            field=models.ImageField(upload_to='modelo/imagens'),
        ),
    ]
