# Generated by Django 4.1.3 on 2022-11-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_alter_conta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cardImage',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
