# Generated by Django 4.1.1 on 2022-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_rename_tipocartão_cartao_tipocartao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagens',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='modelo/cliente'),
        ),
    ]
