# Generated by Django 4.1.3 on 2022-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_conta_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='data_movimentacao',
            field=models.DateField(auto_now=True),
        ),
    ]
