# Generated by Django 4.1.1 on 2022-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='agencia',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numeroConta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=9, unique=True),
        ),
    ]
